sudo: false

branches:
  only:
    - 6.x
    - master
    - replace_feature

language: java
install: ./gradlew b
script: ./gradlew integrationTest
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle
