sudo: false

branches:
  only:
    - 6.x

language: java
install: ./gradlew b
script: ./gradlew integrationTest
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle
